# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_facility_formreviewofs_formros_formvitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('history_data_ref', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.HistoryData')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
