# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160315_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData_test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.BigIntegerField()),
                ('tobacco', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('history_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HistoryData_test')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
