# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160315_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='med_his',
        ),
        migrations.RemoveField(
            model_name='test',
            name='med_his2',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
