branch-defaults:
  default:
    environment: remotehcs
    group_suffix: null
global:
  application_name: prod_openemr_api
  default_ec2_keyname: groupkey
  default_platform: python2.7
  default_region: us-east-1
  profile: eb-cli
  sc: null
