#!/bin/bash

# This script will start the Django server in the background on port 8000.

echo 
echo starting...
python manage.py runserver 0.0.0.0:8000 > /dev/null 2>&1 &
echo Django server started in background
echo
