# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('authorized', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('mname', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('federaltaxid', models.CharField(blank=True, max_length=255, null=True)),
                ('federaldrugid', models.CharField(blank=True, max_length=255, null=True)),
                ('upin', models.CharField(blank=True, max_length=255, null=True)),
                ('facility', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_id', models.IntegerField()),
                ('see_auth', models.IntegerField()),
                ('active', models.IntegerField()),
                ('npi', models.CharField(blank=True, max_length=15, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('billname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('email_direct', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('assistant', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('valedictory', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=60, null=True)),
                ('streetb', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('street2', models.CharField(blank=True, max_length=60, null=True)),
                ('streetb2', models.CharField(blank=True, max_length=60, null=True)),
                ('city2', models.CharField(blank=True, max_length=30, null=True)),
                ('state2', models.CharField(blank=True, max_length=30, null=True)),
                ('zip2', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
                ('phonew1', models.CharField(blank=True, max_length=30, null=True)),
                ('phonew2', models.CharField(blank=True, max_length=30, null=True)),
                ('phonecell', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cal_ui', models.IntegerField()),
                ('taxonomy', models.CharField(max_length=30)),
                ('ssi_relayhealth', models.CharField(blank=True, max_length=64, null=True)),
                ('calendar', models.IntegerField()),
                ('abook_type', models.CharField(max_length=31)),
                ('pwd_expiration_date', models.DateField(blank=True, null=True)),
                ('pwd_history1', models.TextField(blank=True, null=True)),
                ('pwd_history2', models.TextField(blank=True, null=True)),
                ('default_warehouse', models.CharField(max_length=31)),
                ('irnpool', models.CharField(max_length=31)),
                ('state_license_number', models.CharField(blank=True, max_length=25, null=True)),
                ('newcrop_user_role', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
