# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=9, null=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=255, null=True)),
                ('group_number', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_lname', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_mname', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_fname', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_ss', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_dob', models.DateField(blank=True, db_column='subscriber_DOB', null=True)),
                ('subscriber_street', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_city', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_state', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_country', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_employer', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_employer_street', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_employer_postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_employer_state', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_employer_country', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_employer_city', models.CharField(blank=True, max_length=255, null=True)),
                ('copay', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('pid', models.BigIntegerField()),
                ('subscriber_sex', models.CharField(blank=True, max_length=25, null=True)),
                ('accept_assignment', models.CharField(max_length=5)),
                ('policy_type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'insurance_data',
                'managed': False,
            },
        ),
    ]
