# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_medicalhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='history_data_ref',
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
