# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_historydata_test_medicalhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='history_data',
        ),
        migrations.DeleteModel(
            name='HistoryData_test',
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
