# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_formencounter_forms_issueencounter_lists_liststouch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('facility_npi', models.CharField(blank=True, max_length=15, null=True)),
                ('service_location', models.IntegerField()),
                ('billing_location', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormReviewofs',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('pid', models.BigIntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('groupname', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized', models.IntegerField(blank=True, null=True)),
                ('dry_mouth', models.CharField(blank=True, max_length=5, null=True)),
                ('heart_attack', models.CharField(blank=True, max_length=5, null=True)),
                ('high_blood_pressure', models.CharField(blank=True, max_length=5, null=True)),
                ('insulin_dependent_diabetes', models.CharField(blank=True, max_length=5, null=True)),
                ('noninsulin_dependent_diabetes', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'form_reviewofs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormRos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('heart_problem', models.CharField(blank=True, max_length=3, null=True)),
                ('p', models.CharField(blank=True, max_length=3, null=True)),
                ('n_numbness', models.CharField(blank=True, max_length=3, null=True)),
                ('n_weakness', models.CharField(blank=True, max_length=3, null=True)),
                ('diabetes', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'form_ros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormVitals',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('pid', models.BigIntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('groupname', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized', models.IntegerField(blank=True, null=True)),
                ('pulse', models.FloatField(blank=True, null=True)),
                ('bps', models.CharField(blank=True, max_length=40, null=True)),
                ('bpd', models.CharField(blank=True, max_length=40, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, db_column='BMI', null=True)),
                ('waist_circ', models.FloatField(blank=True, null=True)),
                ('activity', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'form_vitals',
                'managed': False,
            },
        ),
    ]
