# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20160315_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('med_his', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign', to='api.MedicalHistory')),
                ('med_his2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onetoone', to='api.MedicalHistory')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='patientdata',
            options={'managed': False},
        ),
    ]
