# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='med_his2',
        ),
    ]
